class UsersConstants:
    URL_SIGNUP = "https://qauto2.forstudy.space/api/auth/signup"
    URL_SIGNIN = "https://qauto2.forstudy.space/api/auth/signin"
    URL_LOGOUT = "https://qauto2.forstudy.space/api/auth/logout"
    URL_PROFILE = "https://qauto2.forstudy.space/api/users/profile"
    URL_DEL_USERS = "https://qauto2.forstudy.space/api/users"
    NAME = "Denis"
    LAST_NAME = "Pupkinnn"
    LOGIN_EMAIL_SETUP = "pupkin_1@test.pup"
    LOGIN_EMAIL_TEST = "pupkin_2@test.pup"
    PASSWORD = "Qwerty12345"
